# Generated by Django 4.2.2 on 2023-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_t2image_remove_table2_images_table2_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='images',
        ),
        migrations.DeleteModel(
            name='T2Image',
        ),
        migrations.AddField(
            model_name='table2',
            name='images',
            field=models.ImageField(null=True, upload_to='T2img'),
        ),
    ]
