# Generated by Django 4.2.2 on 2023-07-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_table3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.table1')),
            ],
        ),
    ]
